### ISSUE TITLE
New paper page should have text input for title, venue, and year

### ISSUE THREAD

**Issue by swt2public** [hpi-swt2-exercise/rails-exercise-17-melvin-witte#22]
### Scenario
When a user visits the new paper page
Then the page should render

### Error
> Got NameError: undefined local variable or method `new_paper_path' for #<RSpec::ExampleGroups::NewPaperPage:0x00000007707e78>
Did you mean?  new_author_path
Did you mean?  new_author_path

*Estimated progress: 60% complete*

**Comment by mewitte** [comment]
Closed by [commit 2aeff4f0a5436b2887a5193b122d14a7568b40e7](https://github.com/hpi-swt2-exercise/rails-exercise-17-melvin-witte/commit/2aeff4f0a5436b2887a5193b122d14a7568b40e7)
